### ISSUE TITLE
Implement as a spdlog plugin?

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/graylog-logger#11]
There is currently some messy code in the file writer and forwarder for logging to file, to console or to graylog. It seems reasonable to support different logging methods as institutions other than ESS may not want to be bound to Graylog.
One nice way of cleaning up that code would be to use https://github.com/gabime/spdlog and incorporate graylog-logger as a plugin. Any thoughts on this @SkyToGround?

**Comment by SkyToGround** [comment]
1. Agreed.
2. I do not want to comment.

**Comment by SkyToGround** [comment]
@matthew-d-jones After having seen spdlog being used by Jason Turner in one of his C++ Weekly episodes, I decided to look at spdlog a bit closer. My initial conclusion is that the library requires some work to implement the features that we want (arbitrary additional fields) but it would probably result in a safer/better logging system in the end.
However, I am not interested in making those changes as what we have now appears to be working without problem and doing nothing is less work than doing something. As for the comment on the file-writer and forwarder, the messiness was/is definitely not caused by the use of this library.
